apiVersion: v3alpha1
service: 
   containers: 
    - name: server
      image: dname:1.00.02.00
      ports: 
        - containerPort: 8080
      resources:
        # 最小申请资源大小。必填。
        requests:
          # cpu时间片大小，以“m”为单位，1000m为一核心。
          cpu: 100m
          # 内存大小。以“Mi”、“Gi”为单位。1024Mi=1Gi。
          memory: 128Mi
        # 最大限制资源大小。必填。
        limits:
          cpu: 1000m
          memory: 1024Mi

       
   ports: 
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
   proxy: 
      paths: 
       - path: /
         servicePort: 80
   replicas: 1
