management:
  health:
    db:
      enabled: false
spring:
  messages:
    basename: i18n/notificationSMS
  application:
    name: notification-sms
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url:  jdbc:mysql://127.0.0.1:3306/sms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC

server:
  port: 8088

supos:
  supos-address: http://47.129.0.177:8080
  app-id: 4d4384283dc193f39d6b95b5db1b8940
  app-secret: 10999785ab1c5f475c6d9c8b728e28a3


supfusion:
#  supos:
#    ak: ${SUPOS_APP_ACCOUNT_ID:default}
#    sk: ${SUPOS_APP_SECRET_KEY:default}
#    supos-host: ${SUPOS_ADDRESS:http://localhost:8080}
#    appId: ${SUPOS_APP_ID:605fd270fb5b3563411572db01634214}

  supos:
    ak: ${SUPOS_APP_ACCOUNT_ID:73101af46504b78d84d3b12fab482777}
    sk: ${SUPOS_APP_SECRET_KEY:50fdd25963042ace27d3963cbe78c065}
    supos-host: ${SUPOS_ADDRESS:http://47.129.0.177:8080}
    appId: ${SUPOS_APP_ID:4d4384283dc193f39d6b95b5db1b8940}

  cloud:
    registry:
      enabled: true
      secure: false
      weight: 1
      group: DEFAULT_GROUP
    i18n:
      enabled: false
      host: http://i18n-service.default.svc.cluster.local:8080
      locale-module: notificationSMS
      module-version: notificationSMS20210407
      basename: i18n/
      use-get-all-module: true
      modules:
        - notificationSMS
    discovery:
      enabled: true
      group: DEFAULT_GROUP
    nacos:
      server-addr: nacos:8848
      username: nacos
      password: nacos
  swagger:
    enable: false
logging:
  level:
    com:
      supcon:
        supfusion:
          notification:
            admin:
              openapi:
                feign: debug
